model: RawNet3
encoder_type: ECA
nOut: 256
sinc_stride: 10
max_frames: 400
batch_size: 28
eval_frames: 500
trainfunc: aamsoftmax
lr: 0.001
lr_decay: 0.75
weight_decay: 5e-05
max_seg_per_spk: 500
augment: True
save_path: exps/RawNet3_AAM_cosine_400
margin: 0.3
test_interval: 8
scheduler: cosineannealing
optimizer: sgd