model: RawNet3
encoder_type: ECA
nOut: 256
sinc_stride: 10
max_frames: 300
batch_size: 72
eval_frames: 400
trainfunc: aamsoftmax
lr_decay: 0.75
weight_decay: 5e-05
max_seg_per_spk: 500
augment: True
save_path: exps/RawNet3_AAM_cosine
margin: 0.3
test_interval: 8
scheduler: cosineannealing
optimizer: sgd